name: satron
description: "A Map for Malaysians"
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # Firebase core
  firebase_core: ^3.12.0

  # env
  flutter_dotenv: ^5.1.0

  # protobuf format
  protobuf: ^4.0.0
  fixnum: ^1.1.1
  protoc_plugin: ^22.0.0
  http: ^1.3.0
  geolocator: ^10.0.0
  csv: ^5.0.2

  # map
  flutter_map: ^8.1.1
  latlong2: ^0.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

  # protoc plugin

flutter:
  uses-material-design: true
  assets:
    - .env
    -

  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Bold.ttf
          weight: 700
        - asset: fonts/Poppins-Medium.ttf
          weight: 500
        - asset: fonts/Poppins-Regular.ttf
          weight: 400
        - asset: fonts/Poppins-SemiBold.ttf
          weight: 600
