name: satron
description: "A Map for Malaysians"
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  intl: ^0.17.0



  # Firebase
  firebase_core: ^2.32.0
  firebase_auth: ^4.19.1
  cloud_firestore: ^4.17.5
  shared_preferences: ^2.2.2
  url_launcher: ^6.1.5

  # env
  flutter_dotenv: ^5.1.0

  # protobuf format
  protobuf: ^4.0.0
  fixnum: ^1.1.1
  protoc_plugin: ^22.0.0
  http: ^1.3.0
  geolocator: ^10.0.0
  csv: ^5.0.2

  # map
  flutter_map: ^8.1.1
  latlong2: ^0.9.0

dev_dependencies:
  flutter_launcher_icons: ^0.9.2
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/Logo.png"

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/images/bus.jpg
    - assets/images/train.jpg
    - assets/images/flight.jpg
    - assets/images/Logo.png
    - assets/images/tng.png
    - assets/images/grab.png
    - assets/images/maybank.png
    - assets/images/public.png
    - assets/images/cimb.png
    - assets/images/ocbc.png
    - assets/images/uob.png


  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Bold.ttf
          weight: 700
        - asset: fonts/Poppins-Medium.ttf
          weight: 500
        - asset: fonts/Poppins-Regular.ttf
          weight: 400
        - asset: fonts/Poppins-SemiBold.ttf
          weight: 600
